### ISSUE TITLE
Patterns

### ISSUE THREAD

**Issue by willirath** [MarcoLandtHayen/MarDATA_Startprojekt#5]
With the SAM index and the ENSO index defined, we should have a look at the associated patterns.

For SAM, we should look at the projection of SLP onto the SAM index, reading roughly like
```python
slp_pattern_sam = (sam * slp).mean("time")
```
where `sam` only has a `"time"` dimension, and `slp` has a `"time"` and other spatial dimensions. Xarray will take care of the broadcasting and the resulting `slp_pattern_sam` should only have the spatial dimensions left.

For ENSO, it would be interesting to first check the SST pattern (analogous to `slp_pattern_sam` above) and verify that indeed it shows the strongest anomalies in the NINO3.4 box used to define the index.

Then, the SLP pattern associated with ENSO is of interest as the argument of Morrow et al. (2011) is that the SLP pattern of positive SAM and positive ENSO anomalies largely cancel each other in the Pacific sector of the Southern Ocean.

**Comment by MarcoLandtHayen** [comment]
Thank you Willi, I will have a closer look at that!
